[build]
  publish = "dist"
  command = "npm run build:netlify"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/tests/attempts/*"
  to = "/.netlify/functions/test-attempts/:splat"
  status = 200

[[redirects]]
  from = "/api/tests/*"
  to = "/.netlify/functions/tests/:splat"
  status = 200

[[redirects]]
  from = "/api/tests"
  to = "/.netlify/functions/tests"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200